# Generated by Django 4.1.1 on 2022-09-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education_students',
            name='education_filial',
        ),
        migrations.RemoveField(
            model_name='education_students',
            name='education_main',
        ),
        migrations.RemoveField(
            model_name='education_students',
            name='group_id',
        ),
        migrations.DeleteModel(
            name='Education_group',
        ),
        migrations.DeleteModel(
            name='Education_students',
        ),
    ]
