# Generated by Django 4.1.1 on 2022-09-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_students',
            name='create_date',
            field=models.DateField(),
        ),
    ]
