# Generated by Django 4.1.1 on 2022-09-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B_authentication', '0001_initial'),
        ('D_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstudent',
            name='education_filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='B_authentication.education_filial'),
            preserve_default=False,
        ),
    ]
